### ISSUE TITLE
Privacy page

### ISSUE THREAD

**Issue by blogdemoi** [holehan/hugo-component-matomo#11]
Hello,

Could you clarify what is the Privacy page? You say 

> Add the optout shortcode to your privacy page

But I have no idea what is the privacy page. I run a Hugo blog and just installed Matomo on my server.

Thank you if you have time to reply.

**Comment by holehan** [comment]
Oh, it's just the page where you want the optout to appear. I simply called it "privacy page" because it's a rather common name for a page that holds a privacy statement with info about what and why one's tracking her users. If you scroll down to the bottom of github.com, you'll notice that GitHub has one too called "Privacy".

**Comment by blogdemoi** [comment]
Thank you.
